# Generated by Django 5.1.7 on 2025-04-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_customuser_post_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
