# Generated by Django 5.1.7 on 2025-04-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_profile_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress',
            new_name='address',
        ),
    ]
